import { TServiceProductData } from "@/interFace/interFace";
import blackSolarPanel from '../../public/assets/img/solar-panel-black.jpeg';
import sp2 from '../../public/assets/img/solar-inverter.jpeg';
import sp3 from '../../public/assets/img/battery-1.jpeg'
import sp4 from '../../public/assets/img/consumption-1.jpeg'
import sp5 from '../../public/assets/img/installation-3.jpeg'
import sp6 from '../../public/assets/img/cleaning-1.jpg'
import sp1 from '../../public/assets/img/solar-panel.jpeg'
import teslaBat from '../../public/assets/img/solar-battery-testla.jpg'

import spt1 from '../../public/assets/img/string-inverter.png'
import spt2 from '../../public/assets/img/micro-inverter.webp'
import spt3 from '../../public/assets/img/growatt.jpg'
import spt31 from '../../public/assets/img/battery-2.png'


export const serviceProductData: TServiceProductData[] = [
    {
        id: 3,
        tagLine: "Before we delve into the cost, it's important to know that different types of solar panels are available to suit various needs, and their costs vary accordingly.",
        img: blackSolarPanel,

        // for top heading
        primaryTitle: "Solar Panels",
        primaryInfo: "The heart of the solar panel system, these panels contain special cells that capture sunlight and convert it into direct current (DC) electricity. Each solar panel consists of silicon solar cells covered by a sheet of glass and held together by a metal frame. When sunlight hits the solar cells, it activates electrons, which then flow through the cell.Wires capture this flow of electrons and combine it with the output of other cells within the panel.Solar panels are classified based on their rated power output in Watts, which indicates the power they can produce in 1 peak sun hour. It's important to note that solar panel output is affected by cell operating temperature. They are an optimum choice to power homes, businesses, and even entire communities.",
        
        secondaryTitle: "Components of a Solar Panel System",
        secondaryInfo: "",

        // if product has type
        types: [
            {
                id: 31,
                title: "Solar Panels",
                details: "The heart of the solar panel system, these panels contain special cells that capture sunlight and convert it into direct current (DC) electricity.Each solar panel consists of silicon solar cells covered by a sheet of glass and held together by a metal frame. When sunlight hits the solar cells, it activates electrons, which then flow through the cell.Wires capture this flow of electrons and combine it with the output of other cells within the panel.Solar panels are classified based on their rated power output in Watts, which indicates the power they can produce in 1 peak sun hour. It's important to note that solar panel output is affected by cell operating temperature.They are an optimum choice to power homes, businesses, and even entire communities.",
                img: sp1,
                btnContent: 'Read More About Solar Panels', 
                btnHref: '/services',
            },
            {
                id: 32,
                title: "Solar Battery",
                details: "A solar battery is a crucial component used to store excess electricity generated by solar panels. A solar battery is a crucial component used to store excess electricity generated by solar panels. It acts like a backup power source, ensuring you have electricity even during nights, cloudy days, or power outages. In a grid-tied solar system, a battery might not be necessary, as it can rely on the power grid for electricity. However, for off-grid solar systems that operate independently, a battery is essential to store and use the energy when there isn't adequate sunlight. In the solar industry, there are different battery options available, with the two main types being lead-acid and lithium batteries.",
                img: sp3,
                btnContent: 'Read More About Solar Battery',
                btnHref: '/services',
            },
            {
                id: 33,
                title: "Solar Inverters",
                details: "Inverters play a vital role in a solar panel system by converting the direct current (DC) electricity generated by solar panels into alternating current (AC) electricity, which powers household appliances and electronic devices.",
                img: sp2,
                btnContent: 'Read More About Solar Inverters',
                btnHref: '/services',
            }

        ],
    },
    {
        id: 5,
        tagLine: "Solar inverters are the unsung heroes of solar energy systems. They convert the DC electricity produced by solar panels into AC electricity that can be used in your home.",
        primaryTitle: "Solar Inverters",
        primaryInfo: "Inverters are crucial components in a solar panel system because they convert the DC electricity produced by the solar panels into the AC electricity needed for our appliances and devices.",
        img: sp2,
        secondaryTitle: "Types of Solar Inverters",

        types: [
            {
                id: 51,
                title: "String Inverter",
                details: "String inverters are commonly used in both residential and commercial solar power systems to manage interconnected chains of solar panels, known as “string circuits. These string circuits consist of solar panels wired together sequentially, and they are linked to the string inverter. It is called a string inverter because it is typically connected to multiple solar panels arranged in strings. These inverters are at the heart of many grid-tied solar power systems, making them an essential component of any solar installation. The inverter includes Maximum Power Point Tracking (MPPT) technology, which constantly monitors the electrical characteristics of the solar panels. MPPT ensures that the inverter operates at the optimal voltage and current levels to maximise the power output from the panels.However, they have a drawback: if one panel in a string is obstructed, the entire string's performance decreases due to sensitivity to individual panel issues. And as more homes, businesses, and industries install solar power across the country, this trend is expected to continue.",
                img: spt1,
            },
            {
                id: 52,
                title: "Micro Inverter",
                details: "Microinverters are small, router-sized devices installed beneath each solar panel. Unlike string inverters, which connect to multiple panels and limit performance to the weakest link, microinverters are installed directly at each panel, with one microinverter dedicated to each. This means that every solar panel operates independently, maximizing energy production. This is why, they are slightly more expensive than string inverters. They also provide precise monitoring capabilities. While central inverters offer only system-level data, microinverters enable you to track the production of each individual panel. This level of granularity empowers you to identify and address issues promptly. Scalability is another key benefit of microinverters. If you plan to expand your solar system, you can easily add microinverters one at a time, offering flexibility and adaptability to your energy needs.",
                img: spt2,
            },
            {
                id: 53,
                title: "Hybrid Inverter",
                details: "A Hybrid Solar Inverter is a versatile device that combines the functions of both a solar inverter and a battery inverter into a single unit. This innovative technology allows solar panels, batteries, and the grid to seamlessly work together. They are an ideal choice for you if you are aiming to install a solar power system with future upgrade potential, including battery storage.These inverters come with several key features: they can intelligently manage power from solar panels, solar batteries, and the utility grid simultaneously, and they can convert energy between AC and DC interchangeably, opening up new possibilities for energy storage. They excel in areas with unreliable grids, providing a stable power supply. They also enable the storage of excess solar energy in batteries for later use. Additionally, they offer reliable backup power during blackouts.",
                img: spt3
            }
        ],

    },
    {
        id: 4,
        tagLine: "Connect your battery to Origin Loop to unlock more value",
        primaryTitle: "Solar Battery",
        primaryInfo: "A solar battery is a crucial component used to store excess electricity generated by solar panels. A solar battery is a crucial component used to store excess electricity generated by solar panels. It acts like a backup power source, ensuring you have electricity even during nights, cloudy days, or power outages. In a grid-tied solar system, a battery might not be necessary, as it can rely on the power grid for electricity. However, for off-grid solar systems that operate independently, a battery is essential to store and use the energy when there isn't adequate sunlight. In the solar industry, there are different battery options available, with the two main types being lead-acid and lithium batteries.",
        img: sp3,
        secondaryTitle: "Why Solar batteries are important?",

        types: [
            {
                id: 41, 
                title: "How Does it Work?",
                details: "This system works like this: Your solar panels produce power, which goes into your battery storage/backup system. The battery charges itself up by taking excess power generated by your solar panels and storing it for later use at night or during cloudy days.When you install a battery system for your home or business, you can use the stored energy as needed throughout the day.",
                img: spt31
            },
            {
                id: 42,
                title: "Benefits of Solar Batteries",
                details: "Solar batteries are a great way to store excess energy generated by your solar panels. They can help you save money on your electricity bills, reduce your carbon footprint, and provide backup power during outages. Solar batteries are a great way to store excess energy generated by your solar panels. They can help you save money on your electricity bills, reduce your carbon footprint, and provide backup power during outages. Solar batteries are a great way to store excess energy generated by your solar panels. They can help you save money on your electricity bills, reduce your carbon footprint, and provide backup power during outages.",
                img: teslaBat
            }
        ]
    },
    {
        id: 6,
        primaryTitle: "Wi-Fi Consumption Monitoring",
        primaryInfo: "Wi-Fi consumption monitoring is a smart way to keep track of your energy usage. It allows you to monitor your energy consumption in real-time, set energy-saving goals, and receive alerts when you exceed your set limits. With Wi-Fi consumption monitoring, you can take control of your energy usage and reduce your electricity bills.",
        img: sp4,
        secondaryTitle: "How Does it Work?",
        secondaryInfo: "Wi-Fi consumption monitoring works by connecting your smart meter to your home Wi-Fi network. The smart meter records your energy usage and sends the data to a cloud-based platform, where you can access it from your smartphone, tablet, or computer. You can view your energy usage in real-time, set energy-saving goals, and receive alerts when you exceed your set limits. With Wi-Fi consumption monitoring, you can take control of your energy usage and reduce your electricity bills.",
    },
    {
        id: 1,
        primaryTitle: "Solar Panel Installation",
        primaryInfo: "Solar panel installation is the process of mounting solar panels on your roof or property to generate electricity from sunlight. The installation process involves several steps, including site assessment, system design, permitting, and installation. Solar panel installation is a great way to reduce your electricity bills, lower your carbon footprint, and increase the value of your property.",
        img: sp5,
    },
    {
        id: 2,
        primaryTitle: "Solar Panel Cleaning",
        primaryInfo: "Solar panel cleaning is the process of removing dirt, dust, and debris from your solar panels to maintain their efficiency and performance. Regular cleaning can help your solar panels generate more electricity and extend their lifespan. Solar panel cleaning is an essential part of solar panel maintenance and can help you get the most out of your solar energy system.",
        img: sp6
    }
];